# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 509364883be813af0b5688d4cf703c181fc1f10a888394d3bbb075afc7e8f6a2bd317c1a0a82c081b92219021fe53ceab79569b4c2756bb2afc5a8de3e505953

  google_client_id: 181046210975-1eh2olgrj5832crnf9tqhtvs7itd5oh2.apps.googleusercontent.com
  google_client_secret: Wq54k6QMML2WGXP2Gr-xwGG8

  facebook_client_id: 423745881741540
  facebook_client_secret: ee92d81f0c8f017bf50dc58b40ae2f89

test:
  secret_key_base: 01f97eab6d31cd67e9148a275aed8d466324c20b19a806503f5c0047b37bbfe4f08fe1f16f3158455a988931e30e3da6ddd6a1b6f7e376e638cb3929bca9b8dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
